### ISSUE TITLE
function F_apa for var.test

### ISSUE THREAD

**Issue by spressi** [cran/apa#1]
When being confronted with ceiling or floor effects, comparison of variances are a good first clue (variance gets restricted). Thus, it would be nice to have an APA output for calls to functions like var.test.

Here is a first crude approach for simple console output:
``` r
F_apa = function(f.test) {
  cat("F(", paste(f.test$parameter, collapse=", "), ") = ", f.test$statistic %>% signif(3),   
  ", p ", ifelse(f.test$p.value < .001, "< .001", paste0("= ", f.test$p.value %>% signif(3))), "\n", sep="")
}

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by spressi** [comment]
Thanks! First issue I have ever posted so I am a bit unoriented :)
